image: alpine:latest

pages:
  stage: deploy

  script:
    - mkdir -p public
    - cp index.html public/
    - cp -r css public/

  artifacts:
    paths:
      - public

  pages: true

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
